What is this??
Appearently some people from local willages heard rummors that you're 
going to attack the enemy and they came to help, with dynamite strapped
around their chests!! This is intolerable...

After listening to the sories how their families were masacred by orks,
the decision was made that they can help.

How this top secret military mission leaked to the local viligers is 
a story we have to investigate some other time.

For now our main objective is to kill as many orks as we can before 
all camp wakes up. The main sleeping area is marked on your map.
Kill them and let's quickly get out of here.

(and dont forget to give those poor people their revange!!)
