Cesta p©es hory je velmi zt¡‘en  t¡m, ‘e v tˆchto hor ch se
usadily divok‚ Harpyje a zarytˆ br n¡ svoje £zem¡. Velmi £‡innˆ
jim v tom pom haj¡ Orkov‚, kte©¡ vˆd¡, ‘e tu jde o mnoho.
P©edpokl d  se tu velmi siln˜ odpor. Jedinou mo‘nost¡ jak
oslabit protivn¡kovy ©ady o Harpyje, je odst©elit ‡ sti skaln¡ho
masivu a zatarasit alespo¤ na ‡as vchody do jeskyn¡. Speci lnˆ
kv–li t‚to misi dorazily dvˆ roty samohybn˜ch minomet– M106.

You still have a choice, if you leave the mission and let 
the cave intact we will face much more enamies next time, 
but possible loot and knowledge in the caves may be worth 
it. On the other hand harpys are fearsome enemies and 
killing as many infant harpys could save our soldiers lives.
Destroying the cave enterances would ruin our chance for 
scavenging!
