K obr nc–m vrchoviny se p©ipojily tak‚ rozzu©en‚ Harpyje. Jejich
dˆsiv˜ k©ik a zpˆv smrti je mo‘n‚ sly¨et i ve velk‚ vzd lenosti.
V˜¨iny obsadili Orkov‚ se sv˜mi bojov˜mi mechanismy. Je mo‘n‚ 
o‡ek vat krut˜ boj do posledn¡ho mu‘e.
This is going to be tough fight, among other things it's necessary
to explore the immidiate vicinity of the caves, and you have to 
expect that harpys will defend their territory.
