Mus¡me se za ka‘dou cenu dostat a‘ k magick‚ Br nˆ, kter  vede
na Other Side. Velitelstv¡ po‡¡t  s t¡m, ‘e jakmile se k n¡
dostaneme, mus¡me se j¡ pokusit zni‡it z d lky. Ale jak p©esnˆ
Br na vypad , ani ‘ dn‚ dal¨¡ podrobnosti n m nen¡ nikdo schopen
ozn mit. Jdeme na slepo. A to je v boji s takov˜m velk˜m vl dcem, 
jak˜m je Dragoth, a nav¡c v boji o samotn˜ z kladn¡ k men jeho 
moci smrtelnˆ nebezpe‡n‚. Spole‡nˆ s draky a jeho vybran˜mi Orky 
Krvav‚ho plamene zde proti n m stoj¡ neskute‡n  moc. A to se 
nepo‡¡t  se situac¡, ‘e by Dragoth mohl p©ivolat z Br ny dal¨¡ 
posily p©¡mo z Other Side. Douf me, ‘e k tomu nedojde i proto, 
‘e n m nic jin‚ho ne‘ doufat nezb˜v .
Unfortunatelly dragoths mighty army is here to greet us 
This is going to be increadibly touhg figh, maybe we should leave
and try to harras other territorys and provoke dragoth to 
send this army to chase us, we should be able to deal with 
them better when they are chasing us and we have the upper hand!

