Abychom dostali pod kontrolu tuto oblast, musˇme zni‡it port ly,
kter‚ zabezpe‡ujˇ zdej¨ˇm oddˇl–m neust l p©ˇsun posil. Ale
hlavnˇm cˇlem je zabˇt nep© telsk‚ho gener la. Musˇme se probˇt
pod silnou nep© telskou palbou do pevnosti a gener la p©ipravit
o ‘ivot. Nejen‘e jeho smrtˇ p©ipravˇme P na br ny Dragotha o
siln‚ho spojence, ale uvedeme ve zmatek tak‚ v¨echny nep© telsk‚
oddˇly na tomto Łzemˇ. Jejich odpor potom lehce zlomˇme.

OH no this was a trap! They were waiting for us, this is going to be
impossible! Retreat immediatelly!!
