Musˇme se za ka‘dou cenu dostat a‘ k magick‚ Br n, kter  vede
na Other Side. Velitelstvˇ po‡ˇt  s tˇm, ‘e jakmile se k nˇ
dostaneme, musˇme se jˇ pokusit zni‡it z d lky. Ale jak p©esn
Br na vypad , ani ‘ dn‚ dal¨ˇ podrobnosti n m nenˇ nikdo schopen
ozn mit. Jdeme na slepo. A to je v boji s takovm velkm vl dcem, 
jakm je Dragoth, a navˇc v boji o samotn z kladnˇ k men jeho 
moci smrteln nebezpe‡n‚. Spole‡n s draky a jeho vybranmi Orky 
Krvav‚ho plamene zde proti n m stojˇ neskute‡n  moc. A to se 
nepo‡ˇt  se situacˇ, ‘e by Dragoth mohl p©ivolat z Br ny dal¨ˇ 
posily p©ˇmo z Other Side. Douf me, ‘e k tomu nedojde i proto, 
‘e n m nic jin‚ho ne‘ doufat nezbv . Nevertheless, as we expected
dragoth most fearsome units are waiting for us!

